### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by nhitz** [nealhitzfield/Totally-not-russia#1]
List of Tasks/Tests: Provide a login specifically for the administrator to access their specific window. Tests include enabling a working login button that takes the administrator to the admin page.

Definition of Done: Admin should be able to login with their correct username and password to access their window.

**Comment by nealhitzfield** [comment]
List of Tasks/Tests: Provide a login specifically for the administrator to access their specific window. Tests include enabling a working login button that takes the administrator to the admin page.

Definition of Done: Admin should be able to login with their correct username and password to access their window.
